### ISSUE TITLE
Support fenced divs with implicit class names and trailing colons

### ISSUE THREAD

**Issue by Witiko** [jgm/lunamark#58]
Pandoc's documentation for fenced divs includes the following example:

``` md
::: Warning ::::::
This is a warning.

::: Danger
This is a warning within a warning.
:::
::::::::::::::::::
```

Pandoc produces the following HTML output for the above input:

``` html
<div class="Warning">
<p>This is a warning.</p>
<div class="Danger">
<p>This is a warning within a warning.</p>
</div>
</div>
```

By contrast, Lunamark does not support implicit classnames (`::: Danger`) and trailing colons (`::: Warning ::::::`) and produces the following output for the above input when the `fenced_divs` extension is enabled:

``` html
<p>::: Warning :::::: This is a warning.</p>

<p>::: Danger This is a warning within a warning. ::: ::::::::::::::::::</p>
```

**Comment by Witiko** [comment]
Ping @Omikhleia.

**Comment by Omikhleia** [comment]
Interesting... The use case for it seems a bit limited though.

**Comment by Witiko** [comment]
Personally, I find `::: class` easier to read and type compared to `::: {.class}`. However, regardless of its usefulness, we should support it if we aim for Pandoc compliance.

**Comment by Omikhleia** [comment]
TBH, my own main use of divs  is `::: { custom-style=... }` (as with docx and "named styles"), or `::: { .poetry ... }` but often with additional key-value pairs too for tuning my poetry environment... So I wouldn't need that alternate syntax much... From the example, it seems that besides some class "shortcut", the intended use ("danger", "warning") is a bit similar to "admonitions" (e.g. as in MkDocs, which uses another syntax extension for that, however, in order to also have a Markdown-enabled "title" to the block so marked...). I am not necessarily after "full" Pandoc compatibility: this small feature doesn't bring any new feature we cannot address in some other way.  But I understand the general rationale for it.
